POST http://127.0.0.1:8000/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "name": "cristian",
    "email": "cristian@mail.com",
    "password": "cristian54321",
    "c_password": "cristian54321"
}

### Autenticacion
POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email" : "cristian@mail.com",
    "password": "cristian54321"
}

### obtener el perfil
GET http://127.0.0.1:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer 5|EpKElzrthbdgdHePsrbcMjZ9Zjx9HrMbd6GrHmG67e137f20

